name: Mirror this repo to gitlab
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  mirror-to-gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: "https://code.fbi.h-da.de/advanced-systems-programming-ws22/x4/gameboy-emulator.git"
          GIT_USERNAME: github-sync
          GIT_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
